In [24]:
import pandas as pd
dataset=pd.read_csv('/content/ENB2012_data (1) (1).csv')

In [25]:
dataset.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [26]:
dataset.dtypes

X1    float64
X2    float64
X3    float64
X4    float64
X5    float64
X6      int64
X7    float64
X8      int64
Y1    float64
Y2    float64
dtype: object

In [27]:
dataset.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

In [28]:
dataset.columns=['Relative Compactness','Surface Area','Wall Area','Roof Area','Overall Height','Orientation','Glazing Area','Glazing Area Dis.','Heating Load','Cooling Load']

In [29]:
dataset.head()

Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
0                  0.98         514.5      294.0     110.25             7.0   
1                  0.98         514.5      294.0     110.25             7.0   
2                  0.98         514.5      294.0     110.25             7.0   
3                  0.98         514.5      294.0     110.25             7.0   
4                  0.90         563.5      318.5     122.50             7.0   

   Orientation  Glazing Area  Glazing Area Dis.  Heating Load  Cooling Load  
0            2           0.0                  0         15.55         21.33  
1            3           0.0                  0         15.55         21.33  
2            4           0.0                  0         15.55         21.33  
3            5           0.0                  0         15.55         21.33  
4            2           0.0                  0         20.84         28.28

In [30]:
from sklearn.preprocessing import Normalizer
nr = Normalizer(copy=False)

X = dataset.drop(['Heating Load','Cooling Load'], axis=1)
X = nr.fit_transform(X)
y = dataset[['Heating Load','Cooling Load']]
X

array([[1.62577463e-03, 8.53531681e-01, 4.87732389e-01, ...,
        3.31790741e-03, 0.00000000e+00, 0.00000000e+00],
       [1.62576344e-03, 8.53525808e-01, 4.87729033e-01, ...,
        4.97682687e-03, 0.00000000e+00, 0.00000000e+00],
       [1.62574778e-03, 8.53517587e-01, 4.87724335e-01, ...,
        6.63570524e-03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.77526625e-04, 8.83516575e-01, 4.01598443e-01, ...,
        3.27835464e-03, 4.37113952e-04, 5.46392440e-03],
       [6.77523793e-04, 8.83512882e-01, 4.01596765e-01, ...,
        4.37112125e-03, 4.37112125e-04, 5.46390156e-03],
       [6.77520153e-04, 8.83508134e-01, 4.01594607e-01, ...,
        5.46387220e-03, 4.37109776e-04, 5.46387220e-03]])

In [32]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler()
X=sc.fit_transform(X)
y=sc.fit_transform(y)


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [34]:
X_train

array([[2.31777643e-01, 9.47953631e-01, 9.14675882e-02, ...,
        4.69746559e-01, 4.76132541e-01, 1.52367413e-01],
       [3.10849523e-01, 9.99927853e-01, 5.44854983e-05, ...,
        2.87466312e-01, 4.95003345e-01, 1.58406269e-01],
       [9.99912691e-01, 2.68069548e-01, 8.10933630e-01, ...,
        9.99970090e-01, 2.49987668e-01, 7.99986791e-01],
       ...,
       [1.28401621e-05, 7.27501837e-01, 3.89822167e-01, ...,
        3.57770012e-01, 4.11703706e-01, 2.63499019e-01],
       [2.31780666e-01, 9.47997506e-01, 9.14729093e-02, ...,
        2.62870370e-01, 4.76134062e-01, 3.04735800e-01],
       [2.31759507e-01, 9.47690386e-01, 9.14356628e-02, ...,
        4.69730699e-01, 4.76123415e-01, 7.61822465e-01]])

In [35]:
import tensorflow.python.keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
model=Sequential()
model.add(Dense(16,input_dim=8,activation='relu'))
model.add(Dense(12,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [36]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [37]:
history=model.fit(X_train,y_train,epochs=1000,batch_size=100)

Epoch 1/1000
7/7 [==============================] - 0s 3ms/step - loss: 0.0835 - accuracy: 0.4430
Epoch 2/1000
7/7 [==============================] - 0s 2ms/step - loss: 0.0814 - accuracy: 0.5831
Epoch 3/1000
7/7 [==============================] - 0s 2ms/step - loss: 0.0805 - accuracy: 0.7687
Epoch 4/1000
7/7 [==============================] - 0s 2ms/step - loss: 0.0802 - accuracy: 0.8567
Epoch 5/1000
7/7 [==============================] - 0s 3ms/step - loss: 0.0801 - accuracy: 0.8893
Epoch 6/1000
7/7 [==============================] - 0s 2ms/step - loss: 0.0801 - accuracy: 0.8941
Epoch 7/1000
7/7 [==============================] - 0s 4ms/step - loss: 0.0800 - accuracy: 0.8909
Epoch 8/1000
7/7 [==============================] - 0s 3ms/step - loss: 0.0800 - accuracy: 0.8909
Epoch 9/1000
7/7 [==============================] - 0s 3ms/step - loss: 0.0799 - accuracy: 0.8909
Epoch 10/1000
7/7 [==============================] - 0s 3ms/step - loss: 0.0799 - accuracy: 0.8909
Epoch 11/1000
7/7 [

In [38]:
import numpy as np

y_pred=model.predict(X_test)
print(y_pred)
pred=list()
for i in range(len(y_pred)) :
  pred.append(np.argmax(y_pred[i]))
test=list()
for i in range(len(y_test)) :
  test.append(np.argmax(y_test[i]))

[[0.52772236 0.47227758]
 [0.55141914 0.4485808 ]
 [0.4973273  0.5026727 ]
 [0.51360506 0.48639497]
 [0.5488861  0.45111388]
 [0.57777786 0.4222221 ]
 [0.53518987 0.46481013]
 [0.5262523  0.47374767]
 [0.52182525 0.47817478]
 [0.5418749  0.4581251 ]
 [0.53490156 0.46509844]
 [0.529958   0.47004196]
 [0.5347205  0.46527955]
 [0.51805604 0.481944  ]
 [0.55160755 0.44839242]
 [0.5270741  0.47292593]
 [0.47698075 0.52301925]
 [0.5348346  0.46516535]
 [0.49699566 0.5030044 ]
 [0.5574521  0.44254792]
 [0.5010358  0.49896422]
 [0.52342874 0.4765713 ]
 [0.5941945  0.40580556]
 [0.5207886  0.4792114 ]
 [0.5563696  0.44363046]
 [0.5258361  0.47416386]
 [0.52877027 0.47122976]
 [0.5283712  0.47162881]
 [0.5501494  0.44985062]
 [0.57714236 0.42285764]
 [0.5616959  0.4383041 ]
 [0.5243584  0.4756416 ]
 [0.5559776  0.44402242]
 [0.55569565 0.44430438]
 [0.56576014 0.4342399 ]
 [0.48444742 0.5155525 ]
 [0.48731264 0.51268744]
 [0.5014887  0.4985113 ]
 [0.531345   0.46865496]
 [0.5268322  0.47316784]


In [39]:
from sklearn.metrics import accuracy_score
a=accuracy_score(pred,test)
print('Accuracy is :',a*100)

Accuracy is : 94.15584415584416
